# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
one_d_array = np.array([1])

# Create a 2-dimensional NumPy array using np.array()
two_d_array = np.array([[2,4],
                       [3,5]])

# Create a 3-dimensional Numpy array using np.array()
three_d_array = np.array([[[1,2,3],
                          [1,2,3],
                          
                          [4,5,6],
                          [4,5,6]]])

one_d_array.shape, two_d_array.shape, three_d_array.shape

((1,), (2, 2), (1, 4, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_d_array.shape, one_d_array.ndim, one_d_array.dtype, one_d_array.size, type(one_d_array)

((1,), 1, dtype('int64'), 1, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
two_d_array.shape, two_d_array.ndim, two_d_array.dtype, two_d_array.size, type(two_d_array)

((2, 2), 2, dtype('int64'), 4, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
three_d_array.shape, three_d_array.ndim, three_d_array.dtype, three_d_array.size, type(three_d_array)

((1, 4, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(two_d_array,
                 index=['Number index 1','Number index 2'],
                 columns=['Number column 1', 'Number column 2'])
df

Number column 1  Number column 2
Number index 1                2                4
Number index 2                3                5

In [12]:
# Create an array of shape (10, 2) with only ones
only_ones = np.ones((10,2))
only_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
only_zeros = np.zeros((7,2,3))
only_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0, 100, 3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr_int = np.random.randint(0, 10, (7,2))
rand_arr_int

array([[8, 1],
       [4, 4],
       [9, 3],
       [3, 9],
       [8, 0],
       [6, 7],
       [0, 6]])

In [22]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_arr_float = np.random.uniform(0,1,(3,5))
rand_arr_float

array([[0.36907416, 0.77514494, 0.97732729, 0.59549046, 0.01412431],
       [0.78917694, 0.55549432, 0.44127527, 0.74866968, 0.26799898],
       [0.05536728, 0.06584749, 0.7308831 , 0.70109983, 0.31452136]])

In [26]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_arr = np.random.randint(0, 10 , (4, 6))
rand_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

A: Seed generates random numbers aligned with the value of the seed hence same numbers will be generated each time

In [29]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_arr_2 = np.random.randint(1, 10, (3,7))

# Find the unique numbers in the array you just created
rand_arr_2, np.unique(rand_arr_2)

(array([[2, 5, 8, 9, 9, 1, 9],
        [7, 9, 8, 1, 8, 8, 3],
        [1, 8, 3, 3, 1, 5, 7]]),
 array([1, 2, 3, 5, 7, 8, 9]))

In [31]:
# Find the 0'th index of the latest array you created
rand_arr_2[0]

array([2, 5, 8, 9, 9, 1, 9])

In [34]:
# Get the first 2 rows of latest array you created
rand_arr_2[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [37]:
# Get the first 2 values of the first 2 rows of the latest array
rand_arr_2[:2, :2]

array([2, 5])

In [39]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_arr_3 = np.random.randint(0, 10, (3,5))
ones_arr_2 = np.ones((3,5))
rand_arr_3, ones_arr_2

(array([[0, 2, 4, 2, 0],
        [4, 9, 6, 6, 8],
        [9, 9, 2, 6, 0]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [43]:
# Add the two arrays together
added = rand_arr_3 + ones_arr_2
added

array([[ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7.,  9.],
       [10., 10.,  3.,  7.,  1.]])

In [41]:
# Create another array of ones of shape (5, 3)
ones_arr_3 = np.ones((5,3))
ones_arr_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
# Try add the array of ones and the other most recent array together
added + ones_arr_3
# fix
added.T + ones_arr_3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

A: Shape is different so matrices can not be added. Must be the same shape to add together

How would you fix it?

A: Transpose the matrix so they can be same shape

In [45]:
# Create another array of ones of shape (3, 5)
ones_arr_4 = np.ones((3,5))
ones_arr_4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
# Subtract the new array of ones from the other most recent array
added - ones_arr_4

array([[0., 2., 4., 2., 0.],
       [4., 9., 6., 6., 8.],
       [9., 9., 2., 6., 0.]])

In [23]:
# Multiply the ones array with the latest array


In [24]:
# Take the latest array to the power of 2 using '**'


In [25]:
# Do the same thing with np.square()


In [26]:
# Find the mean of the latest array using np.mean()


In [27]:
# Find the maximum of the latest array using np.max()


In [28]:
# Find the minimum of the latest array using np.min()


In [29]:
# Find the standard deviation of the latest array


In [30]:
# Find the variance of the latest array


In [31]:
# Reshape the latest array to (3, 5, 1)


In [32]:
# Transpose the latest array


What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [34]:
# Perform a dot product on the two newest arrays you created


In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [36]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [39]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='


In [41]:
# Find which elements of the first array are greater than 7


In [42]:
# Which parts of each array are equal? (try using '==')


In [43]:
# Sort one of the arrays you just created in ascending order


In [44]:
# Sort the indexes of one of the arrays you just created


In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.