# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_d_array = np.array([1])

# Create a 2-dimensional NumPy array using np.array()
two_d_array = np.array([[2,4],
                       [3,5]])

# Create a 3-dimensional Numpy array using np.array()
three_d_array = np.array([[[1,2,3],
                          [1,2,3],
                          
                          [4,5,6],
                          [4,5,6]]])

one_d_array.shape, two_d_array.shape, three_d_array.shape

((1,), (2, 2), (1, 4, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_d_array.shape, one_d_array.ndim, one_d_array.dtype, one_d_array.size, type(one_d_array)

((1,), 1, dtype('int64'), 1, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
two_d_array.shape, two_d_array.ndim, two_d_array.dtype, two_d_array.size, type(two_d_array)

((2, 2), 2, dtype('int64'), 4, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
three_d_array.shape, three_d_array.ndim, three_d_array.dtype, three_d_array.size, type(three_d_array)

((1, 4, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(two_d_array,
                 index=['Number index 1','Number index 2'],
                 columns=['Number column 1', 'Number column 2'])
df

Number column 1  Number column 2
Number index 1                2                4
Number index 2                3                5

In [7]:
# Create an array of shape (10, 2) with only ones
only_ones = np.ones((10,2))
only_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
only_zeros = np.zeros((7,2,3))
only_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0, 100, 3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr_int = np.random.randint(0, 10, (7,2))
rand_arr_int

array([[3, 9],
       [9, 8],
       [6, 6],
       [4, 6],
       [6, 0],
       [8, 8],
       [0, 9]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_arr_float = np.random.uniform(0,1,(3,5))
rand_arr_float

array([[0.49226623, 0.00370985, 0.85041153, 0.4277357 , 0.12339131],
       [0.53369462, 0.63687883, 0.26790589, 0.1076864 , 0.45410127],
       [0.26333668, 0.68589952, 0.59285253, 0.25622483, 0.7117633 ]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_arr = np.random.randint(0, 10 , (4, 6))
rand_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

A: Seed generates random numbers aligned with the value of the seed hence same numbers will be generated each time

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_arr_2 = np.random.randint(1, 10, (3,7))

# Find the unique numbers in the array you just created
rand_arr_2, np.unique(rand_arr_2)

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 array([1, 2, 3, 4, 5, 7, 9]))

In [14]:
# Find the 0'th index of the latest array you created
rand_arr_2[0]

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
# Get the first 2 rows of latest array you created
rand_arr_2[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
rand_arr_2[:2, :2]

array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_arr_3 = np.random.randint(0, 10, (3,5))
ones_arr_2 = np.ones((3,5))
rand_arr_3, ones_arr_2

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [18]:
# Add the two arrays together
added = rand_arr_3 + ones_arr_2
added

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
ones_arr_3 = np.ones((5,3))
ones_arr_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Try add the array of ones and the other most recent array together
added + ones_arr_3
# fix
added.T + ones_arr_3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

A: Shape is different so matrices can not be added. Must be the same shape to add together

How would you fix it?

A: Transpose the matrix so they can be same shape

In [21]:
# Create another array of ones of shape (3, 5)
ones_arr_4 = np.ones((3,5))
ones_arr_4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Subtract the new array of ones from the other most recent array
added - ones_arr_4

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [29]:
# Multiply the ones array with the latest array
multiply_arr = ones_arr_4 * added
multiply_arr

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [28]:
# Take the latest array to the power of 2 using '**'
exp = multiply_arr**2
exp

array([[ 49.,  64.,   9.,   1.,  16.],
       [  4.,  64.,  16.,   4.,  36.],
       [ 36., 100.,  16.,  36.,   4.]])

In [32]:
# Do the same thing with np.square()
squared = np.square(exp)
squared

598 ns ± 22.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
590 ns ± 1.95 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [33]:
# Find the mean of the latest array using np.mean()
mean_val = np.mean(exp)
mean_val

In [27]:
# Find the maximum of the latest array using np.max()
max_val = np.max(exp)
max_val

In [28]:
# Find the minimum of the latest array using np.min()
min_val = np.min(exp)
min_val

In [34]:
# Find the standard deviation of the latest array
std_val = np.std(exp)
std_val

In [35]:
# Find the variance of the latest array
var_val = np.var(exp)
var_val

771.8222222222224

In [36]:
# Reshape the latest array to (3, 5, 1)
reshape_arr = np.reshape(exp, (3,5,1))
reshape_arr

array([[[ 49.],
        [ 64.],
        [  9.],
        [  1.],
        [ 16.]],

       [[  4.],
        [ 64.],
        [ 16.],
        [  4.],
        [ 36.]],

       [[ 36.],
        [100.],
        [ 16.],
        [ 36.],
        [  4.]]])

In [37]:
# Transpose the latest array
reshape_arr_T = reshape_arr.T

What does the transpose do?

A: Flips the axes of data, so columns become rows and vice versa

In [39]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_ran_1 = np.random.randint(0,10, (3,3))
# arr_ran_1 = np.reshape(arr_ran_1, (3,3))
arr_ran_2 = np.random.randint(0,10, (3,2))
# arr_ran_2 = np.reshape(arr_ran_2, (3,2))
arr_ran_1.shape, arr_ran_2.shape

((3, 3), (3, 2))

In [42]:
# Perform a dot product on the two newest arrays you created
dot_arr = np.dot(arr_ran_1, arr_ran_2)
dot_arr

array([[16, 40],
       [14, 70],
       [14, 71]])

In [43]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_ran_3 = np.random.randint(0,10, (4,3))
arr_ran_4 = np.random.randint(0,10, (4,3))

In [45]:
# Perform a dot product on the two newest arrays you created
dot_arr_2 = np.dot(arr_ran_3, arr_ran_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

A: dot_arr_2 = np.dot(arr_ran_3, arr_ran_4.T)

In [47]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dot_arr_2 = np.dot(arr_ran_3, arr_ran_4.T)
dot_arr_2

array([[111,  57,  60, 105],
       [100,  52,  56,  96],
       [ 30,  37,  18,   4],
       [ 85,  42,  50,  87]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

A: This is due to the column size of the first matrix matching the row size of the second matrix used in the calculation 

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [60]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_ran_5 = np.random.randint(0, 10, (3,2))
arr_ran_6 = np.random.randint(0, 10, (3,2))
arr_ran_5, arr_ran_6

(array([[3, 6],
        [7, 0],
        [5, 7]]),
 array([[4, 3],
        [1, 5],
        [5, 0]]))

In [61]:
# Compare the two arrays with '>'
arr_ran_5 > arr_ran_6

array([[False,  True],
       [ True, False],
       [False,  True]])

What happens when you compare the arrays with `>`?

A: Compares each element in one matrix with its corresponding in the other matrix to see if the boolean operand holds true. When it is a single row array with the same number of columns as the matrix it is to be compared to, each element in the single row is compared against the each element in the other matrix's column

In [62]:
# Compare the two arrays with '>='
arr_ran_5 >= arr_ran_6

array([[False,  True],
       [ True, False],
       [ True,  True]])

In [63]:
# Find which elements of the first array are greater than 7
arr_ran_5[arr_ran_5 > 7]

array([], dtype=int64)

In [64]:
# Which parts of each array are equal? (try using '==')
arr_ran_5 == arr_ran_6

array([[False, False],
       [False, False],
       [ True, False]])

In [65]:
# Sort one of the arrays you just created in ascending order
sorted_1 = np.sort(arr_ran_5)
sorted_1

array([[3, 6],
       [0, 7],
       [5, 7]])

In [73]:
# Sort the indexes of one of the arrays you just created
sorted_idx = np.argsort(sorted_1)
sorted_idx

array([[0, 1],
       [0, 1],
       [0, 1]])

In [75]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(sorted_idx)
max_index

1

In [76]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(sorted_idx)
min_index

0

In [77]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_index = np.argmax(sorted_idx, axis=1)
max_index

array([1, 1, 1])

In [78]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_index = np.argmin(sorted_idx, axis=1)
min_index

array([0, 0, 0])

In [71]:
# Create an array of normally distributed random numbers
norm_dis = np.random.normal(0,1,(1,5))
norm_dis

array([[ 0.88751161,  0.60548313, -0.72029799, -0.26993377, -0.14346223]])

In [68]:
# Create an array with 10 evenly spaced numbers between 1 and 100
even_spaced = np.linspace(1,100,10)
even_spaced

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.